{{- if .Values.staticIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ printf "plendy-%s" .Values.service.name }}'
  labels:
    {{- include "plendy.labels" $ | nindent 4 }}
    app.kubernetes.io/name: '{{ .Values.service.name }}'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  rules:
   - host: {{ .Values.staticIngress.host }}
     http:  
      paths:
      - path: {{ .Values.staticIngress.path }}
        pathType: Prefix
        backend:
          service:
            name: '{{ printf "plendy-%s" .Values.service.name }}'
            port: 
              number: 8000
{{- end }}